<?php
require("config.php");
require("read.php");

$file = file_get_contents($FILE_NAME);
$bookmark = json_decode($file);
?>

<!DOCTYPE html>
<html>
    <head>
        <title>My Bookmarks</title>
        <link rel="stylesheet" type="text/css" href="css/style.css" />
    </head>
    <body>
        <header>
        </header>
            <?php echo read($bookmark);?>

        <footer>
            Generated by <a href="https://github.com/jishnu7/publish-your-bookmarks">Publish Your Bookmarks</a>.
        </footer>
    </body>
</html>



